### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by KenshiHH** [litui/hyperhdr-shield-watcher#2]
Hey,
just tested your script, overwall it works fine but there is a problem, the code runs without any kind of pause or limit on how often the loop runs each second.

im running it on a proxmox container with 1 core and 1GB of Ram,

with your current script it takes up 100% CPU Usage.

with a small modification,

"import time"

and adding

"time.sleep(3)"

after adbh.loop() at line 54

the cpu usage went down to 0.08% without any negative perfomance issues on switching between hdr and sdr

added a pull request
https://github.com/litui/hyperhdr-shield-watcher/pull/3

**Comment by litui** [comment]
Oh hey, thanks for the fix! I'll review quick and get it in ASAP.
